# Copyright (c) LieberLIeber SOftware GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# The purpose of this workflow is to upload LemonTree Component Files (*.mpms) to a Nexus repository in order to be reused by other models.
# You can download them from nexus to the reusing workstation from the Nexus
# The latest release will be stored in the main folder, specific versions in a folder for each release.

# Future Ideas:
# * Upload to GitHub Release
# * Run checks before publish

name: LTA publish components on Release

on:
  release:
    types: [created]

env:
  ModelName: ArchimateModel
  ModelExtension: qeax
  ReviewSessionURL: https://nexus.lieberlieber.com/repository/LemonTree.ArchiMate.Demo/lemontree-component/

jobs:
  LTAPublishComponentsOnRelease:
    defaults:
      run:
        shell: pwsh
    runs-on: [ubuntu-latest]
    timeout-minutes: 15
    
    steps:
      - name: checkout from GitHub
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Extract version from tag
        id: get_version
        uses: battila7/get-version-action@v2.2.1
                      
      # download Lemontree.Automation on a runner and setup the license
      - name: GetLTA
        uses: LieberLieber/setup-LemonTree.Automation@v5
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}} 
        #ExeLocation &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}"

      - name: Publish LemonTree Components
        run: |
          &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}" publish --Model ${{env.ModelName}}.${{env.ModelExtension}} --PackageDirectory "." --All

      - name: Archive Component Files
        uses: actions/upload-artifact@v4
        with:
          name: ArchiMateModelComponents_${{ steps.get_version.outputs.version}}
          path: "*.mpms"
          retention-days: 2

      - name: Upload LemonTree Components to Nexus
        run: |
          $files = Get-ChildItem *.mpms
          foreach ($file in $files) 
          {
            $sfName =  $file.Name
            $sfNameUri = [uri]::EscapeDataString($sfName)
            $targetUrlLatest = "${{env.ReviewSessionURL}}$sfNameUri"
            $targetUrlVersion = "${{env.ReviewSessionURL}}/${{ steps.get_version.outputs.version}}/$sfNameUri"
            
            while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
            
            Write-Output "Uploading $sfName to Nexus: $targetUrlLatest"
            curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T "$sfName" "$targetUrlLatest"
            
            Write-Output "Uploading $sfName to Nexus: $targetUrlVersion"
            curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T "$sfName" "$targetUrlVersion"
          }
         
   

    
